### ISSUE TITLE
Gamemode not recognized by server

### ISSUE THREAD

**Issue by Kiwi-1995** [glua/terrortown_gold#1]
As title says. Isn't recognized by server.

Working path on test server that I have:
GarrysModDS/garrysmod/gamemodes/tttgold

Launch options:
./srcds_run -console -game garrysmod -gamemode tttgold +hostname "FPGMF" +sv_password *********** -tickrate 30 +map ttt_richland

**Comment by Kefta** [comment]
It's because of the info.txt - it now has to be the gamemode's name. I want to try finding exactly what was added to the base TTT so this can be moved over to a newer version, or be rewritten.
